server:
  port: 8081
spring:
  application:
    name: config-client
  ## 开启消息跟踪
  cloud:
    bus:
      trace:
        enabled: true

  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest
management:
  endpoints:
    web:
      exposure:
        include: "*"
